import { product, changes, jurisdictions, tools, evidenceLayers } from './data.js';
import { publicShell, icon, button, sectionHead, status } from './lib.js';

const heroStats = Object.entries(product.corpus).map(([key,value]) => {
  const labels={issueBriefs:['Deep issue briefs','Curated legal intelligence'],jurisdictions:['State + D.C. guides','Effective-dated comparisons'],hotelLaws:['Hotel-specific laws','Wage, benefit, workload, retention'],tools:['Inspectable workflows','Inputs, logic, sources, outputs']};
  return `<div><strong>${value}</strong><span>${labels[key][0]}</span><small>${labels[key][1]}</small></div>`;
}).join('');

function platform() {
  const hero=`<section class="hero"><div class="hero-copy"><span class="kicker"><i></i> Hospitality wage-and-hour intelligence</span><h1>See the change.<br>Know the impact.<br><em>Prove the response.</em></h1><p>The control plane that connects verified legal authority to properties, people, payroll systems, accountable actions, executive decisions, and operating evidence.</p><div class="hero-actions">${button('Enter portfolio command →','/app/','accent')}${button('See how the system works','#operating-model','ghost')}</div><div class="trustline"><span>${icon('shield')} Source governed</span><span>${icon('calendar')} Effective dated</span><span>${icon('source')} Passage cited</span><span>${icon('eye')} Gaps disclosed</span></div></div><div class="hero-product"><header><span><i></i> Active enterprise matter</span><button data-command>${icon('spark')} Ask</button></header><div class="matter-head"><div><small>MTR-2026-041 · SOUTHERN CALIFORNIA</small><h2>Los Angeles hotel wage step</h2><p>Effective July 1, 2026 · 7 properties under review</p></div>${status('Decision due','critical')}</div><ol class="flow"><li><span>${icon('source')}</span><div><small>Verified authority</small><strong>Hotel wage and benefit step</strong><p>Primary law · effective date · approved rule</p></div><b>Current</b></li><li><span>${icon('building')}</span><div><small>Portfolio applicability</small><strong>7 properties · 842 employees</strong><p>Locality · room count · workforce · benefits</p></div><b>2 gaps</b></li><li><span>${icon('shield')}</span><div><small>Accountable response</small><strong>3 controls · 4 owners</strong><p>Payroll · benefits · testing · evidence</p></div><b>In progress</b></li><li><span>${icon('decision')}</span><div><small>Executive decision</small><strong>Controlled implementation</strong><p>Recommendation · conditions · provenance</p></div><b>Jun 16</b></li></ol><footer><span><strong>96%</strong><small>record completeness</small></span><span><strong>3</strong><small>primary authorities</small></span><span><strong>1</strong><small>disclosed fact gap</small></span><a href="/app/matters/">Open matter →</a></footer></div><div class="hero-stats">${heroStats}</div></section>`;
  const model=`<section class="public-section" id="operating-model">${sectionHead('The operating model','Legal intelligence is only useful when it survives the handoff.','A development should not be summarized in one system, analyzed in another, assigned in email, briefed in slides, and proven in a shared drive. One governed record should carry the law, facts, analysis, ownership, decision, and evidence.')}<div class="chain"><article><span>01</span>${icon('signal')}<h3>Detect change</h3><p>Capture the source, changed rule, version, effective date, and materiality.</p><small>AUTHORITY GRAPH</small></article><article><span>02</span>${icon('building')}<h3>Resolve reach</h3><p>Apply effective-dated law to property, workforce, pay, benefit, and system facts.</p><small>APPLICABILITY ENGINE</small></article><article><span>03</span>${icon('matter')}<h3>Govern response</h3><p>Carry findings into owners, actions, controls, evidence requests, and exceptions.</p><small>MATTER GRAPH</small></article><article><span>04</span>${icon('decision')}<h3>Preserve decision</h3><p>Give leadership a concise recommendation without severing it from its basis.</p><small>DECISION RECORD</small></article></div></section>`;
  const plane=`<section class="dark-section"><div>${sectionHead('The control plane','One record from authority to assurance.','Every experience is a view of the same governed object graph—not a disconnected dashboard, calculator, article, or slide deck.')}<ul class="checklist"><li>${icon('check')} One rule version across every surface</li><li>${icon('check')} One effective-dated property fact model</li><li>${icon('check')} Deterministic logic separated from counsel judgment</li><li>${icon('check')} Decisions linked to operating proof</li><li>${icon('check')} Revalidation when a dependency changes</li></ul>${button('Inspect the evidence standard →','/methodology/','ghost')}</div><div class="mini-app"><header><span>North America portfolio</span><small>Current through Jun 13, 2026</small></header><div class="mini-kpis"><span><small>Material decisions</small><strong>3</strong><b>2 due in 7 days</b></span><span><small>Open matters</small><strong>7</strong><b>4 on track</b></span><span><small>Control assurance</small><strong>87%</strong><b>+5 pts</b></span></div><article><small>MATTER MTR-2026-041</small><h3>Los Angeles hotel wage step</h3><p>7 properties · 842 employees · July 1 effective date</p><div class="lifecycle"><span class="done">Assess</span><span class="active">Decide</span><span>Implement</span><span>Assure</span></div><footer><span>1 fact gap · 3 controls</span><a href="/app/matters/">Open matter →</a></footer></article></div></section>`;
  const roles=`<section class="public-section">${sectionHead('One system · role-relevant emphasis','Shared truth without shared noise.','Every leader sees the depth appropriate to the decision they own. No role gets a divergent version of the law or facts.')}<div class="role-grid"><article>${icon('decision')}<small>GENERAL COUNSEL</small><h3>Material posture and decisions</h3><p>What changed, which obligations are material, what judgment is required, and whether the response remains defensible.</p><a href="/app/">Open portfolio command →</a></article><article>${icon('book')}<small>EMPLOYMENT COUNSEL</small><h3>Facts, analysis, and authority</h3><p>Resolve scope, inspect every proposition, model alternatives, approve findings, and draft the decision.</p><a href="/app/matters/">Open governed matter →</a></article><article>${icon('calculator')}<small>PAYROLL + HR</small><h3>Configuration and action</h3><p>Translate findings into effective-dated rate tables, populations, testing, and communications.</p><a href="/app/controls/">Open control assurance →</a></article><article>${icon('building')}<small>HOTEL OPERATIONS</small><h3>Property obligations and proof</h3><p>Know what applies, what process changes, who owns it, and what evidence must be retained.</p><a href="/app/properties/">Open property intelligence →</a></article></div></section>`;
  const evidence=`<section class="evidence-band"><div>${sectionHead('Trust architecture','Authority is a chain—not a badge.','Source text, enterprise fact, calculation, legal judgment, and response evidence never collapse into one opaque confidence score.')}${button('Read the evidence standard →','/methodology/','primary')}</div><ol>${evidenceLayers.map(([n,t,d,s])=>`<li><span>${n}</span><div><strong>${t}</strong><p>${d}</p></div><b>${s}</b></li>`).join('')}</ol></section>`;
  return publicShell('/',`${hero}${model}${plane}${roles}${evidence}`);
}

function intelligence() {
  const cards=changes.map((c,i)=>`<article class="signal-card ${i===0?'signal-card--lead':''}"><time>${c.date}</time><div><small>${c.id} · ${c.jurisdiction}</small><h3>${c.title}</h3><p>${c.reach}. The change remains linked to its authority, effective date, affected rule, and revalidation state.</p><footer>${status(c.status,c.materiality==='critical'?'critical':c.materiality==='high'?'warn':'info')}<a href="/app/changes/">Open response →</a></footer></div></article>`).join('');
  const families=[['01','Tips & service charges',['Tip credit','Tip pooling','Service charges']],['02','Pay computation',['Overtime & regular rate','Minimum wage','Hotel ordinances','Housekeeper pay']],['03','Workforce structure',['Exemptions','Independent contractors','Joint employer']],['04','Time & scheduling',['Off-the-clock work','Meal & rest breaks','Scheduling']],['05','Enforcement & special populations',['Recordkeeping','Tax & payroll','PAGA & class actions','Seasonal workers','Minors']]];
  return publicShell('/intelligence/',`<section class="subhero"><div><span class="kicker"><i></i> The authority graph</span><h1>Legal intelligence that knows <em>what it changes.</em></h1><p>Developments, issues, jurisdictions, and tools connect through effective-dated sources and rules—so downstream records can be revalidated when law moves.</p>${button('See material developments →','#developments','accent')}</div><aside class="corpus">${heroStats}</aside></section><section class="public-section" id="developments">${sectionHead('Change intelligence','Not every update deserves the same response.','Materiality is triaged against authority, effective date, issue family, jurisdiction, and likely hotel relevance.')}<div class="signals">${cards}</div></section><section class="public-section alt">${sectionHead('Issue architecture','Eighteen legal questions. One connected rule system.','Each issue begins with a direct answer, then exposes scope, effective date, authority, factual dependencies, computation, uncertainty, and operational consequence.')}<div class="family-grid">${families.map(([n,t,items])=>`<article><span>${n}</span><h3>${t}</h3><ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul><a href="#">Explore issue family →</a></article>`).join('')}</div></section>`);
}

function jurisdictionPage() {
  const cards=jurisdictions.map(j=>`<button class="jurisdiction jurisdiction--${j.tier}" data-jurisdiction='${JSON.stringify(j)}'><strong>${j.code}</strong><small>${j.name}</small><b>Tier ${j.tier}</b></button>`).join('');
  return publicShell('/jurisdictions/',`<section class="subhero"><div><span class="kicker"><i></i> Jurisdiction intelligence</span><h1>Know the rule.<br>Then resolve <em>the property.</em></h1><p>State and District of Columbia records establish legal architecture. Hotel-specific local laws and governed property facts determine the operational answer.</p></div><aside class="metrics"><span><strong>51</strong><small>State + D.C. records</small></span><span><strong>19</strong><small>Hotel-specific laws</small></span><span><strong>4</strong><small>Complexity tiers</small></span><span><strong>100%</strong><small>Lineage target</small></span></aside></section><section class="public-section">${sectionHead('Fifty-one records','Explore architecture before property facts change the answer.','Complexity tiers summarize interacting state, local, industry, scheduling, tip, break, and remedies layers. They are transparent triage—not legal outcomes.')}<div class="jurisdiction-tools"><label>${icon('search')}<input data-jurisdiction-search placeholder="Search state or code"></label><div><button class="active" data-tier="all">All</button><button data-tier="4">Tier 4</button><button data-tier="3">Tier 3</button><button data-tier="2">Tier 2</button><button data-tier="1">Tier 1</button></div></div><div class="jurisdiction-layout"><div class="jurisdiction-grid">${cards}</div><aside class="jurisdiction-detail" data-jurisdiction-detail><span class="code">CA</span><small>SELECTED JURISDICTION</small><h2>California</h2>${status('Tier 4 complexity','critical')}<dl><div><dt>Wage floor</dt><dd>$16.90+</dd></div><div><dt>Tip architecture</dt><dd>No tip credit</dd></div><div><dt>Overtime</dt><dd>Daily + weekly</dd></div><div><dt>Hotel layer</dt><dd>Extensive local hotel laws</dd></div></dl><p>A jurisdiction guide is not a property-specific legal determination.</p>${button('Resolve a property →','/app/properties/','primary')}</aside></div></section>`);
}

function toolsPage() {
  const cards=tools.map(t=>`<article class="tool-card" data-tool-family="${t.family}"><span>${t.id}</span>${icon(t.family==='audit'?'calculator':t.family==='planning'?'chart':t.family==='risk'?'scale':'building')}<small>${t.family.toUpperCase()}</small><h3>${t.title}</h3><p>${t.description}</p><dl><div><dt>Inputs</dt><dd>${t.inputs}</dd></div><div><dt>Output</dt><dd>${t.output}</dd></div></dl><footer><b>Inspectable workflow</b><button data-action="demo">Open →</button></footer></article>`).join('');
  return publicShell('/tools/',`<section class="subhero"><div><span class="kicker"><i></i> Inspectable workflows</span><h1>The output is not the product.<br><em>The process is.</em></h1><p>A serious legal tool preserves scope, inputs, assumptions, rule versions, branch trace, math, citations, limitations, and downstream action.</p></div><aside class="contract"><strong>Every tool must expose</strong>${['Fact provenance','Rule and source versions','Branch trace','Assumptions and gaps','Review state','Save-to-matter behavior'].map((x,i)=>`<span><b>0${i+1}</b>${x}${icon('check')}</span>`).join('')}</aside></section><section class="public-section">${sectionHead('Ten workflows','Do the work without hiding the basis.','Prototype calculations remain illustrative until their legal specifications, source versions, fixtures, and attorney approvals are production validated.')}<div class="filter"><button class="active" data-tool-filter="all">All</button><button data-tool-filter="audit">Audit</button><button data-tool-filter="planning">Planning</button><button data-tool-filter="risk">Risk</button><button data-tool-filter="assessment">Assessment</button><button data-tool-filter="design">Design</button></div><div class="tool-grid">${cards}</div></section>`);
}

function methodology() {
  const layers=evidenceLayers.map(([n,t,d,s])=>`<article><span>${n}</span>${icon(n==='01'?'source':n==='04'?'database':n==='05'?'code':n==='06'?'scale':'shield')}<small>${s}</small><h3>${t}</h3><p>${d}</p></article>`).join('');
  return publicShell('/methodology/',`<section class="subhero methodology"><div><span class="kicker"><i></i> Evidence and governance standard</span><h1>Every conclusion should expose <em>why it can be trusted.</em></h1><p>The platform distinguishes source authority, official guidance, approved analysis, enterprise fact, deterministic logic, counsel judgment, and operating evidence.</p></div><aside class="method-proof"><strong>Supportability contract</strong>${['Authority identified','Effective date resolved','Scope stated','Facts sourced','Logic inspectable','Judgment named','Gaps disclosed'].map((x,i)=>`<span><b>0${i+1}</b>${x}${icon('check')}</span>`).join('')}</aside></section><section class="public-section">${sectionHead('Seven evidence layers','Trust is structural—not ornamental.','Each layer has a distinct owner, version, validation standard, and downstream invalidation consequence.')}<div class="method-grid">${layers}</div></section><section class="dark-section single"><div>${sectionHead('Revalidation lifecycle','A changed dependency must find every affected conclusion.','Source supersession, rule approval, material fact change, evidence expiration, and control exception events should trigger governed revalidation—not silent staleness.')}</div><ol class="revalidation"><li><b>01</b><strong>Source changes</strong><span>Version preserved</span></li><li><b>02</b><strong>Rule re-evaluates</strong><span>Dependencies traversed</span></li><li><b>03</b><strong>Objects invalidate</strong><span>Findings and decisions flagged</span></li><li><b>04</b><strong>Owner responds</strong><span>Approval restored or withdrawn</span></li></ol></section>`);
}

export function renderPublic(route) {
  return route==='/'?platform():route==='/intelligence/'?intelligence():route==='/jurisdictions/'?jurisdictionPage():route==='/tools/'?toolsPage():methodology();
}
